apiVersion: batch/v1
kind: Job
metadata:
  namespace: elastic
  name: auditbeat-template-init-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-elasticsearch
        image: appropriate/curl
        resources: {}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - "sh"
        - "-c"
        - "while [ $(curl -sw %{http_code} http://elasticsearch-master.${NAMESPACE}.svc.cluster.local:9200/_cluster/health?pretty -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
      - name: create-auditbeat-template
        image: docker.elastic.co/beats/auditbeat:7.9.1
        command: [ "auditbeat", "setup", "--template",
          "-E", "output.kafka.enabled=false",
          "-E", 'output.elasticsearch.hosts=["elasticsearch-master.elastic.svc.cluster.local:9200"]' ]
      - name: force-kibana-new-documents
        image: "appropriate/curl"
        command: ["curl", "-XDELETE", "elasticsearch-master.elastic.svc.cluster.local:9200/auditbeat-*"]
      restartPolicy: Never