apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: elastic
  labels:
    app: apm-server
spec:
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: appropriate/curl
          resources: {}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - "sh"
          - "-c"
          - "while [ $(curl -sw %{http_code} http://kibana.${NAMESPACE}.svc.cluster.local:5601/api/status -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:7.9.2
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 100Mi
        ports:
        - containerPort: 8200
          name: apm-port
        volumeMounts:
        - name: apm-server-config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
      volumes:
      - name: apm-server-config
        configMap:
          name: apm-server-config
