apiVersion: batch/v1
kind: Job
metadata:
  namespace: elastic
  name: apm-template-init-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-elasticsearch
        image: appropriate/curl
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "sh"
        - "-c"
        - "while [ $(curl -sw %{http_code} http://elasticsearch.${NAMESPACE}.svc.cluster.local:9200/_cluster/health?pretty -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
      - name: create-apm-template
        image: docker.elastic.co/apm/apm-server:7.9.2
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: [ "apm-server", "setup", "--template",
          "-E", "output.kafka.enabled=false",
          "-E", 'output.elasticsearch.hosts=["elasticsearch.elastic.svc.cluster.local:9200"]']
      - name: force-kibana-new-documents
        image: "appropriate/curl"
        imagePullPolicy: IfNotPresent
        command: ["curl", "-XDELETE", "elasticsearch.elastic.svc.cluster.local:9200/apm-*"]
      restartPolicy: Never