apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic
  labels:
    app: kibana-config
data:
  kibana.yml: |-
    # elasticsearch:
    #   hosts: http://elasticsearch-master:9200
    
    monitoring.ui.container.elasticsearch.enabled: true