apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  namespace: elastic
  labels:
    app: logstash
spec:
  serviceName: logstash
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-elasticsearch
          image: appropriate/curl
          resources: {}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - "sh"
          - "-c"
          - "while [ $(curl -sw %{http_code} http://elasticsearch-master.${NAMESPACE}.svc.cluster.local:9200/_cluster/health?pretty -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.9.1
          args:
          - "--debug"
          imagePullPolicy: IfNotPresent
          ports:
            - name: monitor
              containerPort: 9600
              protocol: TCP
            - containerPort: 5555
              name: beats
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: monitor
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: monitor
            initialDelaySeconds: 20
          resources:
            limits:
              cpu: 1000m
              memory: 1536Mi
            requests:
              cpu: 100m
              memory: 1536Mi
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx1g -Xms1g"
          volumeMounts:
            - mountPath: /usr/share/logstash/data
              name: data
            - name: logstash-config
              mountPath: /usr/share/logstash/logstash.yml
              subPath: logstash.yml
            - name: logstash-config-pipeline
              mountPath: /usr/share/logstash/pipeline
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-config-pipeline
          configMap:
            name: logstash-config-pipeline
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: premium-expansion-enabled
        resources:
          requests:
            storage: "50Gi"