apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packetbeat
  namespace: elastic
  labels:
    app: packetbeat
spec:
  selector:
    matchLabels:
      app: packetbeat
  template:
    metadata:
      labels:
        app: packetbeat
    spec:
      securityContext:
        runAsUser: 0
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: packetbeat
      initContainers:
        - name: wait-for-elasticsearch
          image: appropriate/curl
          resources: {}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - "sh"
          - "-c"
          - "while [ $(curl -sw %{http_code} http://elasticsearch-master.${NAMESPACE}.svc.cluster.local:9200/_cluster/health?pretty -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
      - name: packetbeat
        image: docker.elastic.co/beats/packetbeat:7.9.1
        imagePullPolicy: Always
        args: [
          "-e"
        ]
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch-master.$(NAMESPACE).svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: KAFKA_HOST
          value: "kafka-0.kafka-headless.$(NAMESPACE)"
        - name: KAFKA_PORT
          value: "9092"
        - name: KIBANA_HOST
          value: "kibana.$(NAMESPACE).svc.cluster.local"
        - name: KIBANA_PORT
          value: "5601"
        volumeMounts:
        - name: config
          mountPath: /usr/share/packetbeat/packetbeat.yml
          readOnly: true
          subPath: packetbeat.yml
        - name: data
          mountPath: /usr/share/packetbeat/data
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: packetbeat-config
      - name: data
        emptyDir: {}