---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elastic
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        # Mounted `filebeat-inputs` configmap:
        path: ${path.config}/inputs.d/*.yml
        # Reload inputs configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "filebeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    queue.mem:
      events: 4096
      flush.timeout: 5s
    
    output.kafka:
      hosts: ["kafka-0.kafka-headless.elastic:9092"]
      topic: 'filebeat'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch-master:9200"]

    # filebeat.autodiscover:
    #   providers:
    #     - type: docker
    #       templates:
    #       - condition:
    #           contains:
    #             docker.container.labels.org.label-schema.name: "kafka"
    #         config:
    #           - module: kafka
    #             log:
    #               enabled: true
    #               var:
    #                 input:
    #                   type: docker
    #                   containers.ids:
    #                     - "${data.docker.container.id}"

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true

    processors:
      - add_cloud_metadata:
      - add_host_metadata: ~
      - drop_event:
          when:
            equals:
              kubernetes.container.name: "filebeat"
      - drop_event:
          when:
            equals:
              kubernetes.container.name: "heapster-nanny"
      - drop_event:
          when:
            equals:
              kubernetes.container.name: "redirector"
      - drop_event:
          when:
            equals:
              kubernetes.container.name: "tunnel-front"
      - drop_event:
          when:
            equals:
              kubernetes.container.name: "metrics-server"
      - drop_fields:
          fields: 
            - "beat.hostname"
            - "beat.name"
            - "beat.version"
            - "input.type"
            - "prospector.type"
            - "stream"
            - "kubernetes.labels.pod-template-hash"
            - "kubernetes.labels.controller-revision-hash"
            - "kubernetes.labels.pod-template-generation"
            - "kubernetes.labels.app"
            - "source"
            - "host.name"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs-config
  namespace: elastic
  labels:
    app: filebeat
data:
  inputs.yml: |-
    # - type: docker
    #   containers.ids:
    #   - "*"
    #   processors:
    #   - add_host_metadata: ~
    #   - add_cloud_metadata: ~
    #   - add_docker_metadata: ~
    #   - add_kubernetes_metadata:
    #       in_cluster: true
    #   - drop_event:
    #       when:
    #         equals:
    #           kubernetes.container.name: "filebeat"
    #   - drop_event:
    #       when:
    #         equals:
    #           kubernetes.container.name: "heapster-nanny"
    #   - drop_event:
    #       when:
    #         equals:
    #           kubernetes.container.name: "redirector"
    #   - drop_event:
    #       when:
    #         equals:
    #           kubernetes.container.name: "tunnel-front"
    #   - drop_fields:
    #       fields: ["beat.hostname", "beat.name", "beat.version"]